name: Compilar Tu Belleza APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Generar APK desde PWA
        uses: pwa-builder/pwa-build-action@v1
        with:
          manifest: manifest.webmanifest
          platform: android
          output: apk

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Tu-Belleza-APK
          path: "*.apk"
          
